# Generated by Django 5.1.4 on 2026-08-29 09:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productvariant_productvariant_retail_gte_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=20, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Розмір знижки')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Діє з')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Діє до')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Порожнє — без обмеження', null=True, verbose_name='Максимум використань')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано разів')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мінімальна сума замовлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сесії (гість)')),
                ('status', models.CharField(choices=[('open', 'Відкритий'), ('converted', 'Перетворений у замовлення')], default='open', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='commerce.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('paid', 'Оплачено'), ('assembling', 'Збирається'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_method', models.CharField(choices=[('np_warehouse', 'Нова Пошта — відділення'), ('np_courier', 'Нова Пошта — курʼєр'), ('ukrposhta', 'Укрпошта')], max_length=20, verbose_name='Спосіб доставки')),
                ('np_city_name', models.CharField(blank=True, max_length=255, verbose_name='Місто (НП)')),
                ('np_city_ref', models.CharField(blank=True, max_length=64, verbose_name='Ref міста (НП)')),
                ('np_warehouse_name', models.CharField(blank=True, max_length=255, verbose_name='Відділення (НП)')),
                ('np_warehouse_ref', models.CharField(blank=True, max_length=64, verbose_name='Ref відділення (НП)')),
                ('ukrposhta_address', models.CharField(blank=True, max_length=512, verbose_name='Адреса (Укрпошта)')),
                ('payment_method', models.CharField(choices=[('card_online', 'Оплата карткою онлайн'), ('cod', 'Післяплата'), ('bank_transfer', 'За реквізитами')], max_length=20, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено'), ('refunded', 'Повернено')], default='unpaid', max_length=20, verbose_name='Статус оплати')),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакції платіжки')),
                ('payment_idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Idempotency-ключ webhook')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума товарів')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вартість доставки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Разом')),
                ('promo_code_snapshot', models.CharField(blank=True, max_length=50, verbose_name='Промокод (текст)')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар клієнта')),
                ('ttn_number', models.CharField(blank=True, max_length=32, verbose_name='ТТН')),
                ('shipping_error', models.TextField(blank=True, verbose_name='Помилка доставки (API)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=512, verbose_name='Назва товару (знімок)')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU (знімок)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю (знімок)')),
                ('qty', models.PositiveIntegerField(verbose_name='Кількість')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума рядка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Замовлення')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='Варіант товару')),
            ],
            options={
                'verbose_name': 'Товар замовлення',
                'verbose_name_plural': 'Товари замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Було')),
                ('to_status', models.CharField(max_length=20, verbose_name='Стало')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Змінив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='commerce.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусу замовлення',
                'verbose_name_plural': 'Історія статусів замовлень',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart', verbose_name='Кошик')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant', verbose_name='Варіант товару')),
            ],
            options={
                'verbose_name': 'Товар у кошику',
                'verbose_name_plural': 'Товари у кошику',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product_variant'), name='uniq_cart_variant')],
            },
        ),
    ]
