# Generated by Django 5.1.4 on 2026-08-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('event_type', models.CharField(choices=[('order_created', 'Замовлення створено'), ('status_changed', 'Змінено статус')], max_length=30, verbose_name='Тип події')),
                ('payload', models.JSONField(default=dict, verbose_name='Дані (снепшот замовлення)')),
                ('status', models.CharField(choices=[('pending', 'Очікує відправки'), ('sent', 'Відправлено'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус відправки')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Відправлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='commerce.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Подія інтеграції (CRM)',
                'verbose_name_plural': 'Події інтеграції (CRM)',
                'ordering': ['-created_at'],
            },
        ),
    ]
