# Generated by Django 5.2.15 on 2026-09-02 12:20

from django.db import migrations, models


def drop_courier_method(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    Order.objects.filter(delivery_method="np_courier").update(delivery_method="np_warehouse")


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_orderintegrationevent'),
    ]

    operations = [
        migrations.RunPython(drop_courier_method, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('np_warehouse', 'Нова Пошта'), ('ukrposhta', 'Укрпошта')], max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_warehouse_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Відділення / поштомат (НП)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref відділення / поштомату (НП)'),
        ),
    ]
