# Generated by Django 5.2.15 on 2026-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_delivery_np_postomat_ukrposhta'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ukrposhta_index',
            field=models.CharField(blank=True, max_length=5, verbose_name='Індекс (Укрпошта)'),
        ),
    ]
