# Generated by Django 5.1.4 on 2026-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_order_stock_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контакт: email'),
        ),
        migrations.AddField(
            model_name='cart',
            name='contact_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакт: ПІБ'),
        ),
        migrations.AddField(
            model_name='cart',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контакт: телефон'),
        ),
    ]
