# Generated by Django 5.1.4 on 2026-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_order_salesdrive_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderintegrationevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Замовлення створено'), ('status_changed', 'Змінено статус'), ('ttn_updated', 'Оновлено ТТН')], max_length=30, verbose_name='Тип події'),
        ),
    ]
