# Generated by Django 5.1.4 on 2026-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('retail_price__gte', models.F('cost_price')), _connector='OR'), name='productvariant_retail_gte_cost'),
        ),
    ]
