# Generated by Django 5.1.4 on 2026-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_productvariant_retail_gte_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/collections/', verbose_name='Зображення (промо на головній)'),
        ),
    ]
