# Generated by Django 5.1.4 on 2026-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=False, help_text='Нижня смуга навігації (3–4 корені). Повний список — у кнопці «Каталог».', verbose_name='Показувати в шапці'),
        ),
    ]
