# Generated by Django 5.1.4 on 2026-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_show_in_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_name',
            field=models.BooleanField(default=True, help_text='Зніми галочку, якщо логотип уже містить назву бренду (щоб не дублювати текст).', verbose_name='Показувати назву на вітрині'),
        ),
    ]
