# Generated by Django 5.1.4 on 2026-09-02 07:30

from django.db import migrations, models

UMBRELLA_SLUGS = ("all-types", "all-ages")


def mark_umbrella_values(apps, schema_editor):
    AttributeValue = apps.get_model("catalog", "AttributeValue")
    AttributeValue.objects.filter(slug__in=UMBRELLA_SLUGS).update(is_umbrella=True)


def unmark_umbrella_values(apps, schema_editor):
    AttributeValue = apps.get_model("catalog", "AttributeValue")
    AttributeValue.objects.filter(slug__in=UMBRELLA_SLUGS).update(is_umbrella=False)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_brand_show_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="show_on_pdp",
            field=models.BooleanField(
                default=True,
                help_text="Зніми галочку, щоб атрибут лишався лише у фільтрах каталогу.",
                verbose_name="Показувати на картці товару",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="is_umbrella",
            field=models.BooleanField(
                default=False,
                help_text="Якщо товар має це значення (напр. «Усі типи»), інші значення тієї ж групи на картці ховаються.",
                verbose_name="Покриває всі значення групи",
            ),
        ),
        migrations.RunPython(mark_umbrella_values, unmark_umbrella_values),
    ]
