# Generated by Django 5.1.4 on 2026-09-02 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_attribute_pdp_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="shade_hex",
            field=models.CharField(
                blank=True,
                help_text="Наприклад #E4C4A8. Якщо завантажене фото свотча — на вітрині показується фото.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                        "Формат #RGB або #RRGGBB",
                    )
                ],
                verbose_name="Колір відтінку (HEX)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="shade_image",
            field=models.ImageField(
                blank=True,
                help_text="Для перламутру, глітеру, duo-chrome — коли HEX не передає колір.",
                upload_to="catalog/shades/",
                verbose_name="Фото відтінку (свотч)",
            ),
        ),
    ]
