# Generated by Django 5.1.4 on 2026-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariant_shade_swatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
    ]
