# Generated by Django 5.1.4 on 2026-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_details',
            field=models.TextField(blank=True, help_text='Показується клієнту при виборі «Оплата за реквізитами»', verbose_name='Реквізити для оплати'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_enabled',
            field=models.BooleanField(default=True, verbose_name='Оплата за реквізитами увімкнена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_payment_enabled',
            field=models.BooleanField(default=False, help_text='Автоматично недоступна на вітрині, поки не заповнені ключі LIQPAY_* у .env', verbose_name='Оплата карткою онлайн увімкнена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cash_on_delivery_enabled',
            field=models.BooleanField(default=True, verbose_name='Післяплата увімкнена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nova_poshta_enabled',
            field=models.BooleanField(default=True, verbose_name='Нова Пошта увімкнена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ukrposhta_enabled',
            field=models.BooleanField(default=True, verbose_name='Укрпошта увімкнена'),
        ),
    ]
