# Generated by Django 5.1.4 on 2026-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sitesettings_bank_transfer_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('icon_label', models.CharField(blank=True, help_text='Наприклад: 01, Sr — показується у колі/бейджі', max_length=4, verbose_name='Позначка (2 символи)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Текст')),
                ('text_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Перевага (головна)',
                'verbose_name_plural': 'Переваги (головна)',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, verbose_name='Адреса / місто'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, null=True, verbose_name='Адреса / місто'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, null=True, verbose_name='Адреса / місто'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(blank=True, default='Київ, Україна', max_length=255, null=True, verbose_name='Адреса / місто'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Зображення банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Мультибрендовий магазин догляду та макіяжу. Підібрані формули, прозорі склади та зручна доставка по Україні.', verbose_name='Підпис банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, default='Мультибрендовий магазин догляду та макіяжу. Підібрані формули, прозорі склади та зручна доставка по Україні.', null=True, verbose_name='Підпис банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ru',
            field=models.TextField(blank=True, default='Мультибрендовий магазин догляду та макіяжу. Підібрані формули, прозорі склади та зручна доставка по Україні.', null=True, verbose_name='Підпис банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_uk',
            field=models.TextField(blank=True, default='Мультибрендовий магазин догляду та макіяжу. Підібрані формули, прозорі склади та зручна доставка по Україні.', null=True, verbose_name='Підпис банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Косметика для вашої природної краси', max_length=255, verbose_name='Заголовок банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, default='Косметика для вашої природної краси', max_length=255, null=True, verbose_name='Заголовок банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='Косметика для вашої природної краси', max_length=255, null=True, verbose_name='Заголовок банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_uk',
            field=models.CharField(blank=True, default='Косметика для вашої природної краси', max_length=255, null=True, verbose_name='Заголовок банера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_promo_text',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500 ₴', max_length=255, verbose_name='Текст верхньої смужки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_promo_text_en',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500 ₴', max_length=255, null=True, verbose_name='Текст верхньої смужки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_promo_text_ru',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500 ₴', max_length=255, null=True, verbose_name='Текст верхньої смужки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_promo_text_uk',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500 ₴', max_length=255, null=True, verbose_name='Текст верхньої смужки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours',
            field=models.CharField(blank=True, default='Пн–Нд 10:00–20:00', max_length=255, verbose_name='Графік роботи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_en',
            field=models.CharField(blank=True, default='Пн–Нд 10:00–20:00', max_length=255, null=True, verbose_name='Графік роботи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_ru',
            field=models.CharField(blank=True, default='Пн–Нд 10:00–20:00', max_length=255, null=True, verbose_name='Графік роботи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_uk',
            field=models.CharField(blank=True, default='Пн–Нд 10:00–20:00', max_length=255, null=True, verbose_name='Графік роботи'),
        ),
    ]
