# Generated by Django 5.1.4 on 2026-08-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('content', '0003_trustbadge_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('popup', 'Popup'), ('inline', 'Інлайн-блок на головній')], default='popup', max_length=20, verbose_name='Джерело')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_leads', to='commerce.promocode', verbose_name='Виданий промокод')),
            ],
            options={
                'verbose_name': 'Email-лід (підписка)',
                'verbose_name_plural': 'Email-ліди (підписки)',
                'ordering': ['-created_at'],
            },
        ),
    ]
