# Generated by Django 5.1.4 on 2026-08-29 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_newsletterlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, help_text='HEX, напр. #C99B9B. Порожнє — використовується дефолт з мокапу.', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору — HEX, напр. #C99B9B', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір акценту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_hover_color',
            field=models.CharField(blank=True, help_text='HEX, напр. #A97878. Порожнє — використовується дефолт з мокапу.', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору — HEX, напр. #C99B9B', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір акценту (hover)'),
        ),
    ]
