# Generated by Django 5.1.4 on 2026-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustbadge',
            name='icon_label',
            field=models.CharField(blank=True, help_text='leaf / truck / award / refresh / headset — SVG у блоці переваг', max_length=32, verbose_name='Ключ іконки'),
        ),
    ]
