# Generated by Django 5.1.4 on 2026-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_sitesettings_free_shipping_threshold_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_body',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Плейсхолдер {phone} — телефон клієнта з замовлення.', verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_body_en',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Плейсхолдер {phone} — телефон клієнта з замовлення.', null=True, verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_body_ru',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Плейсхолдер {phone} — телефон клієнта з замовлення.', null=True, verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_body_uk',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Плейсхолдер {phone} — телефон клієнта з замовлення.', null=True, verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_number_label',
            field=models.CharField(blank=True, default='Номер замовлення', help_text='Перед номером, напр. «Номер замовлення». Сам номер підставляється автоматично.', max_length=255, verbose_name='Дякуємо — підпис до номера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_number_label_en',
            field=models.CharField(blank=True, default='Номер замовлення', help_text='Перед номером, напр. «Номер замовлення». Сам номер підставляється автоматично.', max_length=255, null=True, verbose_name='Дякуємо — підпис до номера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_number_label_ru',
            field=models.CharField(blank=True, default='Номер замовлення', help_text='Перед номером, напр. «Номер замовлення». Сам номер підставляється автоматично.', max_length=255, null=True, verbose_name='Дякуємо — підпис до номера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_number_label_uk',
            field=models.CharField(blank=True, default='Номер замовлення', help_text='Перед номером, напр. «Номер замовлення». Сам номер підставляється автоматично.', max_length=255, null=True, verbose_name='Дякуємо — підпис до номера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_title',
            field=models.CharField(blank=True, default='Дякуємо за замовлення!', max_length=255, verbose_name='Дякуємо — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_title_en',
            field=models.CharField(blank=True, default='Дякуємо за замовлення!', max_length=255, null=True, verbose_name='Дякуємо — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_title_ru',
            field=models.CharField(blank=True, default='Дякуємо за замовлення!', max_length=255, null=True, verbose_name='Дякуємо — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_title_uk',
            field=models.CharField(blank=True, default='Дякуємо за замовлення!', max_length=255, null=True, verbose_name='Дякуємо — заголовок'),
        ),
    ]
