# Generated by Django 5.1.4 on 2026-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_sitesettings_thank_you_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='thank_you_body',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Можна змінювати слова навколо. Фрагмент {phone} не чіпайте і не перекладайте — на його місце підставиться телефон клієнта з замовлення. Якщо прибрати {phone}, телефон на сторінці не з’явиться.', verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='thank_you_body_en',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Можна змінювати слова навколо. Фрагмент {phone} не чіпайте і не перекладайте — на його місце підставиться телефон клієнта з замовлення. Якщо прибрати {phone}, телефон на сторінці не з’явиться.', null=True, verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='thank_you_body_ru',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Можна змінювати слова навколо. Фрагмент {phone} не чіпайте і не перекладайте — на його місце підставиться телефон клієнта з замовлення. Якщо прибрати {phone}, телефон на сторінці не з’явиться.', null=True, verbose_name='Дякуємо — текст під номером'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='thank_you_body_uk',
            field=models.TextField(blank=True, default='Ми зателефонуємо на {phone} для підтвердження. Статус можна відстежити, написавши нам номер замовлення.', help_text='Можна змінювати слова навколо. Фрагмент {phone} не чіпайте і не перекладайте — на його місце підставиться телефон клієнта з замовлення. Якщо прибрати {phone}, телефон на сторінці не з’явиться.', null=True, verbose_name='Дякуємо — текст під номером'),
        ),
    ]
