# Generated by Django 5.2.15 on 2026-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_currency_uah_to_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_body',
            field=models.TextField(blank=True, default='Спробуйте оплатити ще раз або оберіть інший спосіб оплати нижче. Замовлення вже створено і чекає на оплату.', help_text='Рекомендація клієнту після помилки оплати карткою. Редагується тут.', verbose_name='Оплата не пройшла — текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_body_en',
            field=models.TextField(blank=True, default='Спробуйте оплатити ще раз або оберіть інший спосіб оплати нижче. Замовлення вже створено і чекає на оплату.', help_text='Рекомендація клієнту після помилки оплати карткою. Редагується тут.', null=True, verbose_name='Оплата не пройшла — текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_body_ru',
            field=models.TextField(blank=True, default='Спробуйте оплатити ще раз або оберіть інший спосіб оплати нижче. Замовлення вже створено і чекає на оплату.', help_text='Рекомендація клієнту після помилки оплати карткою. Редагується тут.', null=True, verbose_name='Оплата не пройшла — текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_body_uk',
            field=models.TextField(blank=True, default='Спробуйте оплатити ще раз або оберіть інший спосіб оплати нижче. Замовлення вже створено і чекає на оплату.', help_text='Рекомендація клієнту після помилки оплати карткою. Редагується тут.', null=True, verbose_name='Оплата не пройшла — текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_title',
            field=models.CharField(blank=True, default='Оплата не пройшла', help_text='Показується на «Дякуємо», якщо карткова оплата неуспішна / ще не оплачено.', max_length=255, verbose_name='Оплата не пройшла — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_title_en',
            field=models.CharField(blank=True, default='Оплата не пройшла', help_text='Показується на «Дякуємо», якщо карткова оплата неуспішна / ще не оплачено.', max_length=255, null=True, verbose_name='Оплата не пройшла — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_title_ru',
            field=models.CharField(blank=True, default='Оплата не пройшла', help_text='Показується на «Дякуємо», якщо карткова оплата неуспішна / ще не оплачено.', max_length=255, null=True, verbose_name='Оплата не пройшла — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_pending_title_uk',
            field=models.CharField(blank=True, default='Оплата не пройшла', help_text='Показується на «Дякуємо», якщо карткова оплата неуспішна / ще не оплачено.', max_length=255, null=True, verbose_name='Оплата не пройшла — заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='topbar_promo_text_en',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500\xa0грн', max_length=255, null=True, verbose_name='Текст верхньої смужки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='topbar_promo_text_ru',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500\xa0грн', max_length=255, null=True, verbose_name='Текст верхньої смужки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='topbar_promo_text_uk',
            field=models.CharField(blank=True, default='Безкоштовна доставка від 1500\xa0грн', max_length=255, null=True, verbose_name='Текст верхньої смужки'),
        ),
    ]
