# Generated by Django 5.1.4 on 2026-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariant_shade_swatch'),
        ('content', '0011_sitesettings_payment_pending_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='h1',
            field=models.CharField(blank=True, help_text='Якщо порожнє — на сторінці показується Заголовок.', max_length=255, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='h1_en',
            field=models.CharField(blank=True, help_text='Якщо порожнє — на сторінці показується Заголовок.', max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='h1_ru',
            field=models.CharField(blank=True, help_text='Якщо порожнє — на сторінці показується Заголовок.', max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='h1_uk',
            field=models.CharField(blank=True, help_text='Якщо порожнє — на сторінці показується Заголовок.', max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='catalog.product', verbose_name='Добірка товарів'),
        ),
    ]
