# Generated by Django 5.2.15 on 2026-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_blogpost_h1_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('eyebrow', models.CharField(blank=True, max_length=255, verbose_name='Рядок над заголовком')),
                ('eyebrow_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рядок над заголовком')),
                ('eyebrow_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рядок над заголовком')),
                ('eyebrow_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рядок над заголовком')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
                ('subtitle_uk', models.TextField(blank=True, null=True, verbose_name='Підзаголовок')),
                ('subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Підзаголовок')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Підзаголовок')),
                ('button_text', models.CharField(blank=True, default='До каталогу', max_length=80, verbose_name='Текст кнопки')),
                ('button_text_uk', models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(blank=True, default='До каталогу', max_length=80, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, default='/katalog/', help_text='Відносний шлях або повний URL, напр. /katalog/ чи /dobirka/aktsii/', max_length=512, verbose_name='Посилання кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/hero/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Банер головної',
                'verbose_name_plural': 'Банери головної',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
