# Generated by Django 5.2.15 on 2026-09-02 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='background_image',
            field=models.ImageField(blank=True, help_text='На весь слайд (desktop і mobile). Порожнє — бежевий фон.', null=True, upload_to='content/hero/bg/', verbose_name='Фонове зображення'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='overlay_blur',
            field=models.PositiveSmallIntegerField(default=10, help_text='0–40. Легкий блюр = 6–12', verbose_name='Блюр фону, px'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='overlay_color',
            field=models.CharField(blank=True, default='#EFE9E1', help_text='HEX світлої підложки поверх фону, напр. #EFE9E1', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору — HEX, напр. #C99B9B', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підложки'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=72, help_text='0 — лише блюр фону, 100 — суцільний колір', verbose_name='Прозорість підложки, %'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/hero/', verbose_name='Зображення справа'),
        ),
    ]
