# Generated by Django 5.1.4 on 2026-09-14 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_herobanner_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_details_en',
            field=models.TextField(blank=True, help_text='Показується клієнту при виборі «Оплата за реквізитами»', null=True, verbose_name='Реквізити для оплати'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_details_ru',
            field=models.TextField(blank=True, help_text='Показується клієнту при виборі «Оплата за реквізитами»', null=True, verbose_name='Реквізити для оплати'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_details_uk',
            field=models.TextField(blank=True, help_text='Показується клієнту при виборі «Оплата за реквізитами»', null=True, verbose_name='Реквізити для оплати'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='overlay_blur',
            field=models.PositiveSmallIntegerField(default=10, help_text='Розмиття саме фото фону (не підложки): 0 = чітке фото, 6–12 = легкий блюр, до 40. Порівнюйте на одному слайді (автопрокрутка перемикає слайди з різними значеннями).', verbose_name='Блюр фону, px'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='overlay_color',
            field=models.CharField(blank=True, default='#EFE9E1', help_text='HEX, напр. #EFE9E1. Видно лише коли «Прозорість підложки» > 0. При 0% колір повністю прозорий — зміна HEX нічого не змінить на вітрині.', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору — HEX, напр. #C99B9B', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підложки'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=72, help_text='Наскільки щільно колір накриває фото: 0 = фото без підложки (колір не видно), 50 = легка вуаль, 100 = суцільний колір без фото. Щоб побачити зміну кольору — поставте 40–80.', verbose_name='Прозорість підложки, %'),
        ),
    ]
