# Generated by Django 5.1.4 on 2026-09-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_bank_transfer_details_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_enabled',
            field=models.BooleanField(default=True, help_text='Вимкніть, щоб сховати прогрес-бар і не застосовувати нульову доставку.', verbose_name='Безкоштовна доставка увімкнена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_np',
            field=models.BooleanField(default=True, verbose_name='Діє для Нової Пошти'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_ukrposhta',
            field=models.BooleanField(default=True, verbose_name='Діє для Укрпошти'),
        ),
    ]
