# Generated by Django 5.1.4 on 2026-08-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True, verbose_name='Ref (API)')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Область')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Місто (НП)',
                'verbose_name_plural': 'Міста (НП)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NPWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True, verbose_name='Ref (API)')),
                ('number', models.CharField(blank=True, max_length=16, verbose_name='Номер відділення')),
                ('description', models.CharField(max_length=512, verbose_name='Опис / адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shipping.npcity', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Відділення (НП)',
                'verbose_name_plural': 'Відділення (НП)',
                'ordering': ['city__name', 'number'],
            },
        ),
    ]
