# Generated by Django 5.2.15 on 2026-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npwarehouse',
            options={'ordering': ['city__name', 'number'], 'verbose_name': 'Відділення / поштомат (НП)', 'verbose_name_plural': 'Відділення / поштомати (НП)'},
        ),
        migrations.AddField(
            model_name='npwarehouse',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Категорія (API)'),
        ),
    ]
