window.NANESI_PRODUCTS = [
  {
    id: "pdrn-cream",
    brand: "whocares",
    title: "Зволожувальний крем для обличчя із веганськими полінуклеотидами whocares Vegan PDRN Cream 50 ml",
    titleShort: "Vegan PDRN Cream 50 ml",
    category: "face-creams",
    categoryLabel: "Догляд за обличчям → Креми",
    volume: "50 мл",
    sku: "000005739",
    ean: "4820268260246",
    inStock: true,
    price: 844,
    oldPrice: 1299,
    costPrice: 620,
    country: "Південна Корея",
    skinType: "Усі типи, у т.ч. чутлива",
    concerns: "Зневоднення, сухість, ослаблений бар’єр, дрібні зморшки, втрата пружності",
    actives: "10% MC-PhytoDNA Rose Complex, 2% Celyscence, 2% ніацинамід, 2% сквалан, Bifida Ferment Lysate, Pepta-5, цераміди, ектоїн",
    description: "Зволожувальний крем для щоденного догляду, який допомагає підтримувати захисний бар’єр шкіри, зменшувати прояви сухості та вікових змін.",
    usage: "Нанести невелику кількість крему на очищену та тонізовану шкіру обличчя вранці та/або ввечері.",
    inci: "Aqua, Butylene Glycol, Caprylic/Capric Triglyceride, Glycerin, Cetyl Ethylhexanoate, Squalane, Niacinamide, 1,2-Hexanediol, Bifida Ferment Lysate…",
    image: "img/products/pdrn-cream.png",
    rating: 4.8,
    reviews: 12,
    badge: "sale",
    tags: ["face", "cream"]
  },
  {
    id: "centella-serum",
    brand: "Purito Seoul",
    title: "Сироватка з екстрактом центелли без ароматизаторів Purito Seoul Wonder Releaf Centella Serum Unscented 60 ml",
    titleShort: "Wonder Releaf Centella Serum 60 ml",
    category: "serums",
    categoryLabel: "Догляд за обличчям → Сироватки",
    volume: "60 мл",
    sku: "8809563100316",
    ean: "8809563100316",
    inStock: true,
    price: 940,
    oldPrice: null,
    costPrice: 681,
    country: "Південна Корея",
    skinType: "Чутлива, також іншим типам",
    concerns: "Чутливість, почервоніння, подразнення, зневоднення, ослаблений бар’єр",
    actives: "Korean Centella Asiatica, ніацинамід, пантенол, Sodium Hyaluronate, Madecassoside, Asiaticoside, пептиди, Ceramide NP, алантоїн",
    description: "Заспокійлива сироватка без ароматизаторів для чутливої шкіри. Допомагає зменшувати почервоніння та дискомфорт.",
    usage: "Після очищення та тонера нанести 2–3 натискання на обличчя та шию. Легко поплескати до вбирання.",
    inci: "Water, Glycerin, Dipropylene Glycol, Propanediol, Centella Asiatica Extract, Butylene Glycol, Niacinamide…",
    image: "img/products/centella-serum.png",
    rating: 4.9,
    reviews: 28,
    badge: "hit",
    tags: ["face", "serum"]
  },
  {
    id: "sunscreen",
    brand: "Purito Seoul",
    title: "Сонцезахисний крем з керамідами Purito Seoul Daily Soft Touch Sunscreen SPF50+ PA++++ 60 ml",
    titleShort: "Daily Soft Touch Sunscreen SPF50+ 60 ml",
    category: "spf",
    categoryLabel: "Сонцезахист SPF → Для обличчя",
    volume: "60 мл",
    sku: "8809563102600",
    ean: "8809563102600",
    inStock: true,
    price: 940,
    oldPrice: null,
    costPrice: 681,
    country: "Південна Корея",
    spf: "SPF50+ PA++++",
    skinType: "Усі типи, у т.ч. чутлива",
    concerns: "Захист від UVA/UVB, фотостаріння, зневоднення",
    actives: "5 видів церамідів, Centella Asiatica, пантенол, токоферол, бісаболол + UV-фільтри",
    description: "Легкий сонцезахисний крем широкого спектра SPF50+ PA++++ без вираженого білого сліду.",
    usage: "Нанести рівномірно як останній етап ранкового догляду за ~15 хвилин до виходу на сонце.",
    inci: "Water, Propanediol, Dibutyl Adipate, Dicaprylyl Carbonate, Diethylamino Hydroxybenzoyl Hexyl Benzoate…",
    image: "img/products/sunscreen.png",
    rating: 4.7,
    reviews: 19,
    badge: "new",
    tags: ["spf", "face"]
  },
  {
    id: "shampoo",
    brand: "whocares",
    title: "Шампунь безсульфатний whocares Balancing Shampoo 300 ml",
    titleShort: "Balancing Shampoo 300 ml",
    category: "shampoo",
    categoryLabel: "Догляд за волоссям → Шампуні",
    volume: "300 мл",
    sku: "000005720",
    ean: "4820268260215",
    inStock: true,
    price: 989,
    oldPrice: null,
    costPrice: 649,
    country: "—",
    skinType: "Шкіра голови: суха та нормальна",
    hairType: "Усі типи волосся",
    concerns: "М’яке очищення, сухість шкіри голови, підтримка балансу себуму",
    actives: "Гідролізований протеїн пшениці, розмарин, кропива, береза, хвощ, деревій, чебрець, кокос",
    description: "Безсульфатний шампунь для делікатного очищення сухої та нормальної шкіри голови.",
    usage: "Нанести на вологу шкіру голови та волосся, помасажувати та ретельно змити. За потреби повторити.",
    inci: "Aqua, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Lauryl Glucoside, Coco-Glucoside…",
    image: "img/products/shampoo.png",
    rating: 4.6,
    reviews: 9,
    badge: null,
    tags: ["hair"]
  },
  {
    id: "bb-cushion",
    brand: "Purito Seoul",
    title: "Кушон з екстрактом центелли Purito Seoul Wonder Releaf Centella BB Cushion №13 Neutral Ivory",
    titleShort: "Centella BB Cushion №13 Neutral Ivory",
    category: "makeup",
    categoryLabel: "Макіяж → Кушони",
    volume: "15 г + рефіл 15 г",
    shade: "№13 Neutral Ivory",
    finish: "Напівматовий, природний",
    sku: "8809563103355",
    ean: "8809563103355",
    inStock: true,
    price: 1350,
    oldPrice: null,
    costPrice: 978,
    country: "Південна Корея",
    spf: "SPF30 PA+++",
    skinType: "Усі типи",
    concerns: "Нерівний тон, почервоніння, пігментні плями",
    actives: "Korean Centella Asiatica, Sodium Hyaluronate, цераміди, ніацинамід, токоферол, аденозин",
    description: "BB-кушон з можливістю нашаровування. Вирівнює тон і приховує недосконалості, зберігаючи природний вигляд.",
    usage: "Набрати засіб пухівкою та нанести легкими притискальними рухами. За потреби нашарувати.",
    inci: "Water, Titanium Dioxide, Methyl Trimethicone, Caprylic/Capric Triglyceride, Cetyl Ethylhexanoate, Zinc Oxide…",
    image: "img/products/bb-cushion.png",
    rating: 4.8,
    reviews: 15,
    badge: "hit",
    tags: ["makeup", "face"]
  }
];
