# Generated by Django 5.1.4 on 2026-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productvariant_productvariant_retail_gte_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (H1)')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок (H1)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок (H1)')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок (H1)')),
                ('path', models.SlugField(allow_unicode=True, help_text='Частина URL після домену, напр. permanentnyj-makiyazh — сторінка відкриється на /permanentnyj-makiyazh/', max_length=255, unique=True, verbose_name='Адреса (без слешів)')),
                ('meta_title', models.CharField(blank=True, max_length=512, verbose_name='SEO title')),
                ('meta_title_uk', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('meta_title_en', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('body', models.TextField(blank=True, help_text='HTML дозволено (той самий редактор, що й для сторінок/блогу).', verbose_name='Текст сторінки')),
                ('body_uk', models.TextField(blank=True, help_text='HTML дозволено (той самий редактор, що й для сторінок/блогу).', null=True, verbose_name='Текст сторінки')),
                ('body_ru', models.TextField(blank=True, help_text='HTML дозволено (той самий редактор, що й для сторінок/блогу).', null=True, verbose_name='Текст сторінки')),
                ('body_en', models.TextField(blank=True, help_text='HTML дозволено (той самий редактор, що й для сторінок/блогу).', null=True, verbose_name='Текст сторінки')),
                ('is_indexed', models.BooleanField(default=True, help_text='Вимкнено — сторінка отримує meta robots noindex,nofollow.', verbose_name='Індексувати (index)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('products', models.ManyToManyField(blank=True, related_name='seo_landing_pages', to='catalog.product', verbose_name='Добірка товарів')),
            ],
            options={
                'verbose_name': 'SEO-посадкова сторінка',
                'verbose_name_plural': 'SEO-посадкові сторінки',
                'ordering': ['title'],
            },
        ),
    ]
