# Generated by Django 5.1.4 on 2026-08-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref міста (НП)'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref відділення (НП)'),
        ),
    ]
