# Generated by Django 5.2.15 on 2026-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_saved_np_city_ref_user_saved_np_warehouse_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_ukrposhta_address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Збережена адреса Укрпошти'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_np_warehouse_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Збережене відділення / поштомат (НП)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref відділення / поштомату (НП)'),
        ),
    ]
