# Generated by Django 5.2.15 on 2026-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delivery_np_postomat_ukrposhta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_ukrposhta_index',
            field=models.CharField(blank=True, max_length=5, verbose_name='Збережений індекс Укрпошти'),
        ),
    ]
