# Generated by Django 5.1.4 on 2026-08-29 09:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productvariant_productvariant_retail_gte_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('scope', models.CharField(choices=[('global', 'Глобально (за замовчуванням)'), ('category', 'Категорія'), ('brand', 'Бренд'), ('product', 'Товар')], max_length=20, verbose_name='Рівень')),
                ('markup_percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Націнка, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markup_rules', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markup_rules', to='catalog.category', verbose_name='Категорія')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markup_rules', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Правило націнки',
                'verbose_name_plural': 'Правила націнки',
                'ordering': ['scope'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', True), ('scope', 'global')), models.Q(('brand__isnull', True), ('category__isnull', False), ('product__isnull', True), ('scope', 'category')), models.Q(('brand__isnull', False), ('category__isnull', True), ('product__isnull', True), ('scope', 'brand')), models.Q(('brand__isnull', True), ('category__isnull', True), ('product__isnull', False), ('scope', 'product')), _connector='OR'), name='markuprule_scope_target_matches')],
            },
        ),
    ]
